### ISSUE TITLE
how to improve the diversity of generative 3d mesh?

### ISSUE THREAD

**Issue by lkyf** [Zhengxinyang/LAS-Diffusion#11]
The shape of the generated model is relatively close to the training data. Are there any suggestions to improve the diversity of the generated model?

**Comment by Zhengxinyang** [comment]
I'm not sure if my understanding of diversity is the same as yours: the purpose of training 3D generative models is to try to generate shapes that are consistent with the distribution of the training data. As for the issue of overfitting, you can refer to Fig. 20 in our paper, where we show our model is capable of generating new shapes.

**Comment by lkyf** [comment]
Thank you for your reply. For example, I only trained on hundreds of 3D models of different categories, and the generated models were almost the same as the training data, did too little training data lead to overfitting?

**Comment by Zhengxinyang** [comment]
Yes, too little training data would lead to overfitting. Data augmentation may alleviate this problem.
