### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by zxhxixi** [Zhengxinyang/LAS-Diffusion#14]
Hello! I came across your fantastic work on GAMES, I noticed that some parts of the code, specifically the metrics section, aren't available. I was wondering if there's a plan to release that part of the code as well. 
The previous wavelet sampled 2048 points on the generated mesh surface, but the data in your Table 4 and the wavelet paper are different. Is it because you "uniformly" sampled the mesh in the paper.
I was wondering if there's a plan to release metrics part of the code as well.

**Comment by Zhengxinyang** [comment]
There may be a few differences: 
1. For the chair category, we generated 1356 (the same number as the test set) shapes to compute the metrics, while wavelet-diffusion generated 2000 shapes to compute;
2. The normalization method for the shapes is different, we scaled each shape to a uniform sphere;
3. For the ground truth data, we used the original mesh in the ShapeNet to sample points;
4. About the "uniformly" sampling strategy, we simply used `trimesh.sample()` to sample points.

For the code for calculating metrics, you can refer to #7. If you have any questions or need further clarification, please don't hesitate to reach out.
