### ISSUE TITLE
which vit model is right

### ISSUE THREAD

**Issue by 1910183821** [Zhengxinyang/LAS-Diffusion#18]
RuntimeError: Error(s) in loading state_dict for VisionTransformer:
	size mismatch for head.weight: copying a param with shape torch.Size([1000, 1280]) from checkpoint, the shape in current model is torch.Size([1024, 1280]).
	size mismatch for head.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([1024]).

**Comment by CRISZJ** [comment]
> RuntimeError: Error(s) in loading state_dict for VisionTransformer: size mismatch for head.weight: copying a param with shape torch.Size([1000, 1280]) from checkpoint, the shape in current model is torch.Size([1024, 1280]). size mismatch for head.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([1024]).

have you solved the problem?

**Comment by CRISZJ** [comment]
I've used this https://huggingface.co/timm/vit_huge_patch14_clip_224.laion2b_ft_in1k/tree/main model. and it works!

**Comment by 1910183821** [comment]
> I've used this https://huggingface.co/timm/vit_huge_patch14_clip_224.laion2b_ft_in1k/tree/main model. and it works!
That's what I used to report the error

**Comment by 1910183821** [comment]
> I've used this https://huggingface.co/timm/vit_huge_patch14_clip_224.laion2b_ft_in1k/tree/main model. and it works!
