### ISSUE TITLE
pytorch-lightning "could not infer the batch_size"

### ISSUE THREAD

**Issue by yhhxt** [Zhengxinyang/LAS-Diffusion#4]
Hello, I encountered an error with pytorch-lightning while using train_sketch.sh. When searching for a solution to this error, I noticed that you also encountered a similar issue. I made changes to the code in the identified dataloader section and specified the batch size, but the problem still persists. How did you solve this problem?
![image](https://github.com/Zhengxinyang/LAS-Diffusion/assets/55875788/5687fee3-6cdf-4865-84dd-94fbd103e6b7)

**Comment by Zhengxinyang** [comment]
What is your version of pytorch-lightning? One way to solve this problem is to remove `track_grad_norm=2` in `Trainer`

**Comment by yhhxt** [comment]
Thank you very much for your quick response. Initially, I was using pytorch-lightning version 1.6.2. I tried upgrading to version 1.7.5, but I still encountered an error. Now, following your advice, I removed the line "track_grad_norm=2", and it is running smoothly without any issues. Thanks
