### ISSUE TITLE
Question about training time

### ISSUE THREAD

**Issue by jdily** [Zhengxinyang/LAS-Diffusion#8]
Hi, thank you for sharing code of this great project.
I have a question regarding the training time of the 2nd step: SDF-diffusion.
Because I cannot find the training time reported in the paper, but I am currently experiencing a very long training time in the 2nd step.
In my setting (with a A6000 GPU), the 1st step takes around 3 hours, but the 2nd step takes around 40 hours for training the reported epoch numbers mentioned in the paper.

Can you provide some training time information based on your experience, that will be super helpful.
Thanks a lot.

**Comment by Zhengxinyang** [comment]
The training time between the two stages should not differ significantly. What data did you use?

**Comment by jdily** [comment]
Hi, me and my collaborators using a custom dataset (simple primitives and their combinations).
I think the data is simpler than the shapenet data used in your paper.
We will try to debug a bit to identify the problem, and will ask further questions if we face new issues.
